apiVersion: v1
data:
  config.json: '{"title":"Frengo - Test GitHub 11","version":"4278fd69-2ddd-47d9-80e4-d56d51aa472b","services":[],"securityInfo":{"/api/openapi/*":{},"/api/openapi":{},"/api/openapi/raw/*":{},"/api/openapi/raw":{}},"baseSwagger":{"swagger":"2.0","consumes":["application/json"],"produces":["application/json"],"securityDefinitions":{"APISecretHeader":{"type":"apiKey","in":"header","name":"secret"}}},"description":"Frengo - Test GitHub 11"}'
kind: ConfigMap
metadata:
  name: swagger-aggregator-config
  labels:
    app.kubernetes.io/part-of: frengo-test-github-11
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
